//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_Alquiler_Vehiculos.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alquileres
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Alquileres()
        {
            this.Pagos = new HashSet<Pagos>();
        }
    
        public int AlquilerId { get; set; }
        public int UsuarioId { get; set; }
        public int VehiculoId { get; set; }
        public int TarifaId { get; set; }
        public int EstadoId { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime FechaFinPactada { get; set; }
        public Nullable<System.DateTime> FechaDevolucion { get; set; }
        public bool TieneDanios { get; set; }
        public decimal CostoDanios { get; set; }
        public decimal MultaRetraso { get; set; }
    
        public virtual EstadosAlquiler EstadosAlquiler { get; set; }
        public virtual Tarifas Tarifas { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        public virtual Vehiculos Vehiculos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pagos> Pagos { get; set; }
    }
}
