//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_Alquiler_Vehiculos.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AlquilerVehiculosEntities : DbContext
    {
        public AlquilerVehiculosEntities()
            : base("name=AlquilerVehiculosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Alquileres> Alquileres { get; set; }
        public virtual DbSet<EstadosAlquiler> EstadosAlquiler { get; set; }
        public virtual DbSet<EstadosVehiculo> EstadosVehiculo { get; set; }
        public virtual DbSet<Pagos> Pagos { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Tarifas> Tarifas { get; set; }
        public virtual DbSet<Telefonos> Telefonos { get; set; }
        public virtual DbSet<TiposTarifa> TiposTarifa { get; set; }
        public virtual DbSet<TiposVehiculo> TiposVehiculo { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
        public virtual DbSet<Vehiculos> Vehiculos { get; set; }
    }
}
