//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_Alquiler_Vehiculos.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pagos
    {
        public int PagoId { get; set; }
        public int AlquilerId { get; set; }
        public decimal Monto { get; set; }
        public System.DateTime FechaPago { get; set; }
        public string EstadoPago { get; set; }
    
        public virtual Alquileres Alquileres { get; set; }
    }
}
