//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_Alquiler_Vehiculos.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Telefonos
    {
        public int TelefonoId { get; set; }
        public int UsuarioId { get; set; }
        public string Numero { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
    }
}
